name: attach

on:
   push:
      branches: [dev]

jobs:
   attach:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: fifsky executing remote ssh commands using key
           uses: fifsky/ssh-action@master
           with:
              host: ${{ secrets.HOST }}
              user: ${{ secrets.USER }}
              key: ${{ secrets.SSH_KEY }}
              args: '-tt'
              command: |
                 echo "실행"
                 pm2 kill
                 cd ./web-fleemarket-02
                 git checkout dev
                 git pull
                 yarn install
                 yarn client build
                 pm2 start yarn --name server -- server start:prod
